pipeline {
  agent any
  environment {
    PYTHONUNBUFFERED = 'TRUE'
    SAGEMAKER_PROJECT_NAME_ID = """${bat(
      returnStdout: true,
      script: 'echo "%SAGEMAKER_PROJECT_NAME%"'
      ).trim()}"""
  }
  stages { stepfunctions
    stage('Build and Install') {
      steps {
      bat '''pip3 install --upgrade --force-reinstall --target $HOME/.local/$SAGEMAKER_PROJECT_NAME_ID . "awscli>1.20.30"  "sagemaker>=2.140.0" "transformers==4.26.1" "datasets[s3]==2.10.1" stepfunctions 
      git clone https://github.com/gsuriano/THExt-1.1.git
      python spacy download en_core_web_lg
      pip3 install -e .[dev]'''
      }
    }
    stage('Update and Run Sagemaker Pipeline') {
      steps {
        withAWS(credentials:"${AWS_CREDENTIAL}",region:"${AWS_REGION}") {
          bat '''python ./pipelines/run_pipeline.py --module-name abalone.pipeline \
          --role-arn %SAGEMAKER_PIPELINE_ROLE_ARN% \
          --tags "[{\\"Key\\":\\"sagemaker:project-name\\", \\"Value\\":\\"%SAGEMAKER_PROJECT_NAME%\\"}, {\\"Key\\":\\"sagemaker:project-id\\", \\"Value\\":\\"%SAGEMAKER_PROJECT_ID%\\"}]" \
          --kwargs "{\\"region\\":\\"%AWS_REGION%\\",\\"role\\":\\"%SAGEMAKER_PIPELINE_ROLE_ARN%\\",\\"default_bucket\\":\\"%ARTIFACT_BUCKET%\\"}"'''
          
          echo "Create/Update of the SageMaker Pipeline and execution completed."
        }
      }
    }
  }
}
